name: Build and Deploy to ECS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPO: ${{ vars.ECR_REPO }}

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir data/
      - run: docker build --compress -t prefect .
      - run: docker save --output data/image.tar prefect
      - uses: actions/upload-artifact@v3
        with:
          name: image
          path: data/
